{"version": 2, "width": 135, "height": 31, "timestamp": 1606293893, "env": {"SHELL": "/bin/bash", "TERM": "xterm-256color"}}
[0.022959, "o", "\u001b]0;root@master:~/test\u0007"]
[0.023876, "o", "[root@master test]# "]
[7.075592, "o", "a"]
[7.245566, "o", "n"]
[7.375469, "o", "s"]
[7.435508, "o", "i"]
[7.655573, "o", "b"]
[8.885611, "o", "l"]
[9.085561, "o", "e"]
[9.495589, "o", "-"]
[9.723517, "o", "p"]
[9.935576, "o", "l"]
[10.113483, "o", "a"]
[11.47557, "o", "y"]
[12.545566, "o", "b"]
[12.953658, "o", "o"]
[13.125682, "o", "o"]
[13.276417, "o", "k"]
[13.395552, "o", " "]
[13.855516, "o", "-"]
[14.075584, "o", "i"]
[14.424602, "o", " "]
[14.760752, "o", "i"]
[14.965571, "o", "n"]
[15.11581, "o", "ventory "]
[17.503546, "o", "m"]
[17.743516, "o", "a"]
[17.905569, "o", "in.yaml "]
[19.125644, "o", "-"]
[19.303586, "o", "-"]
[19.885621, "o", "a"]
[20.423499, "o", "s"]
[20.555585, "o", "k"]
[21.455524, "o", "-"]
[21.815464, "o", "v"]
[21.855558, "o", "a"]
[22.126603, "o", "u"]
[22.383556, "o", "l"]
[22.545456, "o", "t"]
[22.805547, "o", "-"]
[23.195578, "o", "p"]
[23.325508, "o", "a"]
[23.623543, "o", "s"]
[23.785565, "o", "s"]
[25.225571, "o", "\r\n"]
[25.630626, "o", "Vault password: "]
[28.825808, "o", "\r\n"]
[28.971317, "o", "/usr/lib/python3.6/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version!\r\n  RequestsDependencyWarning)\r\n"]
[29.353357, "o", "\r\nPLAY [all] ****************************************************************************************************************************\r\n"]
[29.365141, "o", "\r\nTASK [Gathering Facts] ****************************************************************************************************************\r\n"]
[31.585554, "o", "\u001b[0;32mok: [master]\u001b[0m\r\n"]
[31.606884, "o", "\r\nTASK [aws : Launch EC2 instance] ******************************************************************************************************\r\n"]
[65.319422, "o", "\u001b[0;33mchanged: [master]\u001b[0m"]
[65.319762, "o", "\r\n"]
[65.339907, "o", "\r\nTASK [aws : ec2_instance_facts] *******************************************************************************************************\r\n"]
[66.657961, "o", "\u001b[0;31mAn exception occurred during task execution. To see the full traceback, use -vvv. The error was: botocore.exceptions.NoCredentialsError: Unable to locate credentials\u001b[0m"]
[66.658397, "o", "\r\n"]
[66.658651, "o", "\u001b[0;31mfatal: [master]: FAILED! => {\"changed\": false, \"module_stderr\": \"FIPS mode initialized\\r\\nShared connection to master closed.\\r\\n\", \"module_stdout\": \"Traceback (most recent call last):\\r\\n  File \\\"/root/.ansible/tmp/ansible-tmp-1606293958.6474183-26681-39947201798671/AnsiballZ__ec2_instance_facts.py\\\", line 102, in <module>\\r\\n    _ansiballz_main()\\r\\n  File \\\"/root/.ansible/tmp/ansible-tmp-1606293958.6474183-26681-39947201798671/AnsiballZ__ec2_instance_facts.py\\\", line 94, in _ansiballz_main\\r\\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\\r\\n  File \\\"/root/.ansible/tmp/ansible-tmp-1606293958.6474183-26681-39947201798671/AnsiballZ__ec2_instance_facts.py\\\", line 40, in invoke_module\\r\\n    runpy.run_module(mod_name='ansible.modules.cloud.amazon._ec2_instance_facts', init_globals=None, run_name='__main__', alter_sys=True)\\r\\n  File \\\"/usr/lib64/python3.6/runpy.py\\\", line 205, in run_module\\r\\n    return _run_module_code(code, init_globals, run_name, mod_spec)\\r\\n  File \\\"/usr/lib64/python3."]
[66.658786, "o", "6/runpy.py\\\", line 96, in _run_module_code\\r\\n    mod_name, mod_spec, pkg_name, script_name)\\r\\n  File \\\"/usr/lib64/python3.6/runpy.py\\\", line 85, in _run_code\\r\\n    exec(code, run_globals)\\r\\n  File \\\"/tmp/ansible_ec2_instance_facts_payload_nt68kmo5/ansible_ec2_instance_facts_payload.zip/ansible/modules/cloud/amazon/_ec2_instance_facts.py\\\", line 564, in <module>\\r\\n  File \\\"/tmp/ansible_ec2_instance_facts_payload_nt68kmo5/ansible_ec2_instance_facts_payload.zip/ansible/modules/cloud/amazon/_ec2_instance_facts.py\\\", line 560, in main\\r\\n  File \\\"/tmp/ansible_ec2_instance_facts_payload_nt68kmo5/ansible_ec2_instance_facts_payload.zip/ansible/modules/cloud/amazon/_ec2_instance_facts.py\\\", line 512, in list_ec2_instances\\r\\n  File \\\"/usr/local/lib/python3.6/site-packages/botocore/paginate.py\\\", line 449, in build_full_result\\r\\n    for response in self:\\r\\n  File \\\"/usr/local/lib/python3.6/site-packages/botocore/paginate.py\\\", line 255, in __iter__\\r\\n    response = self._make_request(current_kwargs)\\r\\n  File \\"]
[66.658851, "o", "\"/usr/local/lib/python3.6/site-packages/botocore/paginate.py\\\", line 332, in _make_request\\r\\n    return self._method(**current_kwargs)\\r\\n  File \\\"/usr/local/lib/python3.6/site-packages/botocore/client.py\\\", line 357, in _api_call\\r\\n    return self._make_api_call(operation_name, kwargs)\\r\\n  File \\\"/usr/local/lib/python3.6/site-packages/botocore/client.py\\\", line 663, in _make_api_call\\r\\n    operation_model, request_dict, request_context)\\r\\n  File \\\"/usr/local/lib/python3.6/site-packages/botocore/client.py\\\", line 682, in _make_request\\r\\n    return self._endpoint.make_request(operation_model, request_dict)\\r\\n  File \\\"/usr/local/lib/python3.6/site-packages/botocore/endpoint.py\\\", line 102, in make_request\\r\\n    return self._send_request(request_dict, operation_model)\\r\\n  File \\\"/usr/local/lib/python3.6/site-packages/botocore/endpoint.py\\\", line 132, in _send_request\\r\\n    request = self.create_request(request_dict, operation_model)\\r\\n  File \\\"/usr/local/lib/python3.6/site-packages/botocore/endpoint.p"]
[66.658958, "o", "y\\\", line 116, in create_request\\r\\n    operation_name=operation_model.name)\\r\\n  File \\\"/usr/local/lib/python3.6/site-packages/botocore/hooks.py\\\", line 356, in emit\\r\\n    return self._emitter.emit(aliased_event_name, **kwargs)\\r\\n  File \\\"/usr/local/lib/python3.6/site-packages/botocore/hooks.py\\\", line 228, in emit\\r\\n    return self._emit(event_name, kwargs)\\r\\n  File \\\"/usr/local/lib/python3.6/site-packages/botocore/hooks.py\\\", line 211, in _emit\\r\\n    response = handler(**kwargs)\\r\\n  File \\\"/usr/local/lib/python3.6/site-packages/botocore/signers.py\\\", line 90, in handler\\r\\n    return self.sign(operation_name, request)\\r\\n  File \\\"/usr/local/lib/python3.6/site-packages/botocore/signers.py\\\", line 162, in sign\\r\\n    auth.add_auth(request)\\r\\n  File \\\"/usr/local/lib/python3.6/site-packages/botocore/auth.py\\\", line 357, in add_auth\\r\\n    raise NoCredentialsError\\r\\nbotocore.exceptions.NoCredentialsError: Unable to locate credentials\\r\\n\", \"msg\": \"MODULE FAILURE\\nSee stdout/stderr for the exact error\", "]
[66.659023, "o", "\"rc\": 1}\u001b[0m\r\n"]
[66.660665, "o", "\r\nPLAY RECAP ****************************************************************************************************************************\r\n"]
[66.660902, "o", "\u001b[0;31mmaster\u001b[0m                     : \u001b[0;32mok=2   \u001b[0m \u001b[0;33mchanged=1   \u001b[0m unreachable=0    \u001b[0;31mfailed=1   \u001b[0m skipped=0    rescued=0    ignored=0   \r\n"]
[66.661003, "o", "\r\n"]
[66.74081, "o", "\u001b]0;root@master:~/test\u0007"]
[66.741184, "o", "[root@master test]# "]
[80.175824, "o", "e"]
[80.485579, "o", "x"]
[80.748492, "o", "i"]
[80.92561, "o", "t"]
[81.145576, "o", "\r\n"]
[81.145835, "o", "exit\r\n"]
